### ISSUE TITLE
Edit tree entries

### ISSUE THREAD

**Issue by wcheek** [seijikohara/json-tree-view-vue3#327]
Thank you for this component. I was lucky to have stumbled upon it.

I've been able to get the component working along with having access to its events. I'm hoping to build a component that will allow me to edit the entries at each level.

Do you have an idea of how to implement this? I was thinking if I could access more events, then I could add some input feature that would allow editing of the data object stored in my Vue instance.

**Comment by seijikohara** [comment]
@wcheek 
Hi,

Thanks for your question.

I'm not currently planning to add an editing feature. I'm always looking for ways to improve my components, but I don't have any specific plans for this feature at the moment.

If you're really in need of editing functionality, you may want to consider using a different component. I'll keep your request in mind for the future.
