### ISSUE TITLE
Long render times for large data

### ISSUE THREAD

**Issue by killjoy1221** [seijikohara/json-tree-view-vue3#330]
I have some json data with around 2000 properties I'm trying to render, but it takes around 3s to render everything.

This line is causing the slowdown. 
https://github.com/seijikohara/json-tree-view-vue3/blob/04fa65a98d33ad04d19dab6073a466d15cdc483b/src/components/JsonTreeViewItem.vue#L14

It's using `v-show` to render the data then hide it. If it was using `v-if`, it wouldn't render everything at once, speeding up initial loads.

This isn't unique to your project. I've also seen the same issue in `vue3-json-component`.

When using the following code to generate chunked data, I've seen speedups from 2000ms total to 50ms initial plus each click to show when switching from `v-show` to `v-if`.

```ts
// {0: [0, 1, 2, ...], 1: [0, 1, 2, ...], ...}
const chunkeddata: Record<number, number[]> = {};
for (let i = 0; i < 100; i++) {
    chunkeddata[i] = [];
    for (let j = 0; j < 100; j++) {
        chunkeddata[i].push(j)
    }
}
```

**Comment by seijikohara** [comment]
Resolved in v0.2.2.
