### ISSUE TITLE
Vite build error

### ISSUE THREAD

**Issue by alxBO** [seijikohara/json-tree-view-vue3#353]
Hi @seijikohara 

I was facing a build issue that could be easily overcome by modifying this : 
    function onClick(data: Data) 
to this 
function onClick(data: Data | ItemData)

Thank you

**Comment by t8** [comment]
Same issue here. File location: /node-modules/json-tree-view-web3/src/components/JsonTreeVueItem.vue  L117.

**Comment by killjoy1221** [comment]
It seems to work unmodified with `vue-tsc@0.39.5`. Using a later version, I have to edit this interface to have a type of `unknown`.

https://github.com/seijikohara/json-tree-view-vue3/blob/d0be1fdf989bfe2bdef3a538742dbc03bf145c2c/src/components/JsonTreeViewItem.vue#L56-L58

```ts
export interface Data {
  [key: string]: unknown;
}
```

**Comment by seijikohara** [comment]
It was modified by a pull request here and released in version 0.2.3.
https://github.com/seijikohara/json-tree-view-vue3/pull/385

**Comment by seijikohara** [comment]
I switched to Vite, and the problem was resolved.
